---
title: "EDAProject"
author: "J. Dante Maurice"
output: html_document
---



```{r}
library(tidyverse)
wwc_shots <- read_csv("https://raw.githubusercontent.com/36-SURE/2025/main/data/wwc_shots.csv")
```

```{r}
wwc_shots %>% group_by(shot.outcome.name) %>% count()
wwc_shots %>% group_by(play_pattern.name) %>% count()
wwc_shots %>% group_by(shot.technique.name) %>% count()
```

```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>% 
  ggplot(aes(x=play_pattern.name, y=Shots))+
  geom_col(aes(colour = Goal, fill=Goal), position="fill")
```


```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>% filter(avevelocity<=100) %>% 
  ggplot(aes(x=avevelocity, y=DistToGoal)) +
  geom_point(aes(color=Goal))
```


```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>% 
  ggplot(aes(x=DefendersBehindBall))+
  geom_bar(aes(colour = Goal, fill=Goal))
```

```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())  %>% 
  ggplot(aes(x=AttackersBehindBall, y=DefendersBehindBall)) +
  geom_point(aes(color=Goal, shape=Goal), alpha=0.5, size=5) 
```


```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>% filter(minute<=90) %>% 
  ggplot(aes(x=minute))+
  geom_bar(aes(colour = Goal, fill=Goal))
```

```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())  %>% 
  ggplot(aes(x=distance.ToD1.360, y=distance.ToD2.360)) +
  geom_point(aes(color=Goal, shape=Goal), alpha=0.5, size=5) 
```


```{r}
View(wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>% mutate(team_name=possession_team.name[[1:1]]))

```


```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())  %>% 
  filter(location.x>=90) %>% 
  ggplot(aes(y=location.x, x=location.y)) +
  geom_point(aes(color=Goal, shape=Goal), alpha=0.5, size=3) 
```


```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())  %>% 
  filter(shot.end_location.z<=3, shot.end_location.y<=45, shot.end_location.y>=36) %>% 
  ggplot(aes(y=shot.end_location.z, x=shot.end_location.y)) +
  geom_point(aes(color=Goal, shape=Goal), alpha=0.5, size=3) 
```

```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())  %>% 
  filter(shot.end_location.z<=3, shot.end_location.y<=45, shot.end_location.y>=36) %>% 
  filter(player.name.GK %in% goalies, shot.outcome.name%in% c("Saved", "Goal")) %>% 
  ggplot(aes(y=shot.end_location.z, x=shot.end_location.y)) +
  geom_point(aes(color=Goal, shape=Goal), alpha=0.5, size=3) +
  facet_wrap(~player.name.GK)
```


```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())  %>% 
  filter(shot.end_location.z<=3, shot.end_location.y<=45, shot.end_location.y>=36) %>% 
  filter(player.name.GK %in% goalies, shot.outcome.name%in% c("Saved", "Goal")) %>% 
  ggplot(aes(y=shot.end_location.z, x=shot.end_location.y)) +
  geom_point(aes(color=Goal, shape=Goal), alpha=0.5, size=3) 
```




```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>%
  ggplot(aes(x=DefArea))+
  geom_histogram(aes(colour = Goal, fill=Goal), position = "fill")
```


```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>%
  ggplot(aes(x=DefendersInCone))+
  geom_bar(aes(colour = Goal, fill=Goal))
```


```{r}
wwc_shots %>% count(shot.outcome.name)
```

```{r}
wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>%
  ggplot(aes(x=DefendersInCone))+
  geom_bar(aes(colour = shot.outcome.name, fill=shot.outcome.name), position='fill')
```


```{r}
goalies=wwc_shots %>% count(player.name.GK) %>% filter(n>=25)
goalies=goalies$player.name.GK[1:length(goalies$player.name.GK)]


wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no')) %>%
  filter(player.name.GK %in% goalies) %>% 
  ggplot(aes(x=player.name.GK))+
  geom_bar(aes(colour = Goal, fill=Goal))

wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no')) %>% filter(shot.outcome.name!="Goal") %>% 
  filter(player.name.GK %in% goalies) %>% 
  ggplot(aes(x=player.name.GK))+
  geom_bar(aes(colour = shot.outcome.name, fill=shot.outcome.name))

wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no')) %>% filter(shot.outcome.name!="Goal") %>% 
  filter(player.name.GK %in% goalies) %>% 
  ggplot(aes(x=player.name.GK))+
  geom_bar(aes(colour = shot.outcome.name, fill=shot.outcome.name), position="fill")
```


```{r}
library(dplyr)

wwc_shots %>%
  mutate(Goal = ifelse(shot.outcome.name == "Goal", 'yes', 'no')) %>%
  filter(shot.outcome.name != "Goal") %>%
  filter(player.name.GK %in% goalies) %>%
  mutate(last_name = sapply(strsplit(player.name.GK, " "), function(x) tail(x, 1))) %>%
   ggplot(aes(x=last_name))+
  geom_bar(aes(colour = shot.outcome.name, fill=shot.outcome.name), position="fill")
  

```



# Filled with old code
```{r}
### Clustering testing ###

k_means=wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n()) %>% 
  filter(player.name.GK %in% goalies, shot.outcome.name%in% c("Goal")) %>% 
  filter(avevelocity<=200) %>% 
  select(shot.end_location.y, shot.end_location.z, DistToGoal, avevelocity, AngleToGoal, DistSGK, location.x,
         location.y)

std_k_means=k_means %>% scale()


kmeans_many_features=std_k_means %>% kmeans(centers=4,nstart=100)

library(factoextra)

kmeans_many_features %>% 
  fviz_cluster(data=std_k_means,
               geom="point",
               ellipse=FALSE)+
  ggthemes::scale_color_colorblind()

k_means_pca=prcomp(k_means, center=TRUE, scale.=TRUE)


k_means_pca %>% fviz_pca_biplot(label='var', alpha.ind=0.25,
                alpha.var=0.75,
                labelsize=5,
                col.var='darkblue',
                repel=TRUE)






wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Saved", "Goal")) %>% 
  filter(avevelocity<=50) %>%
  ggplot(aes(DistSGK, avevelocity, color=Goal)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()








test=wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Saved", "Goal")) %>% 
  select(shot.end_location.y, shot.end_location.z)

testk=test %>% mutate(shot.end_location.z=as.numeric(scale(shot.end_location.z)), 
                      shot.end_location.y=as.numeric(scale(shot.end_location.y)))




std_kmeans=testk %>% 
  kmeans(algorithm = "Lloyd",
         centers=4,
         nstart=50)

wwc_shots%>% 
  mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Saved", "Goal")) %>% 
  mutate(cluster=factor(std_kmeans$cluster)) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=cluster)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()+
  facet_wrap(~shot.outcome.name)
  

wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Saved", "Goal")) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=shot.body_part.name)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()

wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Saved", "Goal")) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=shot.technique.name)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()

wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Saved", "Goal")) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=position.name)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()


test=wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Goal")) %>% 
  select(shot.end_location.y, shot.end_location.z)

testk=test %>% mutate(shot.end_location.z=as.numeric(scale(shot.end_location.z)), 
                      shot.end_location.y=as.numeric(scale(shot.end_location.y)))




std_kmeans=testk %>% 
  kmeans(algorithm = "Lloyd",
         centers=4,
         nstart=50)

testk %>% mutate(cluster=factor(std_kmeans$cluster)) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=cluster)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()



wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Goal")) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=shot.body_part.name)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()


wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Goal")) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=position.name)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()


wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Goal", "Saved"), player.name.GK %in% most_scored_on,
         shot.end_location.y<=50) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=player.name.GK)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()+
  facet_wrap(~shot.outcome.name)


most_scored_on=wwc_shots %>% group_by(player.name.GK) %>% filter(shot.outcome.name=="Goal") %>% 
  count() %>% arrange(desc(n)) %>% select(player.name.GK) %>% head(6)
most_scored_on=most_scored_on[[1]]



most_goals=wwc_shots %>% group_by(player.name) %>% filter(shot.outcome.name=="Goal") %>% 
  count() %>% arrange(desc(n)) %>% select(player.name) %>% head(6)
most_goals=most_goals[[1]]

wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Goal", "Saved"), player.name %in% most_goals,
         shot.end_location.y<=50) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=player.name)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()+
  facet_wrap(~shot.outcome.name)


most_goals_team=wwc_shots %>% group_by(possession_team.name) %>% filter(shot.outcome.name=="Goal") %>% 
  count() %>% arrange(desc(n)) %>% select(possession_team.name) %>% head(3)
most_goals_team=most_goals_team[[1]]

wwc_shots %>% mutate(Goal=ifelse(shot.outcome.name=="Goal", 'yes','no'), Shots=n())%>% 
  filter(shot.outcome.name%in% c("Goal", "Saved"), possession_team.name %in% most_goals_team,
         shot.end_location.y<=50) %>% 
  ggplot(aes(shot.end_location.y, shot.end_location.z, color=possession_team.name)) + 
  geom_point()+
  ggthemes::scale_color_colorblind()+
  facet_wrap(~shot.outcome.name)






```









