---
title: "First_doc"
author: "Ella Sylvester"
format: pdf
---



```{r}
library(tidyverse)
library(janitor)
library(dplyr)

# wrangling
wwc_shots <- read_csv("https://raw.githubusercontent.com/36-SURE/2025/main/data/wwc_shots.csv")
View(wwc_shots)

shots <- wwc_shots |>
  mutate(goal = if_else(shot.outcome.name == "Goal", "Goal", "Miss"), 
         under_pressure = if_else(under_pressure == "TRUE", "Yes", "No")) |>
  clean_names()
```



## clustering of made goals, first attempt
```{r}
shots_made <- shots |>
  filter(goal == "Goal") |>
  select(location_x, 
         location_y) |>
  scale() |>
  as.data.frame()

first_kmeans <- shots_made |>
  kmeans(centers = 3, nstart = 30)  

 
shots_made |>
   mutate(cluster = factor(first_kmeans$cluster)) |>
   ggplot(aes(x = location_x, 
              y = location_y, 
              color = cluster)) +
   geom_point(size = 2) +
   ggthemes::scale_color_colorblind()
```

## clustering of all shot attempts
```{r}
second_kmeans <- shots_clean |>
  kmeans(centers = 3, nstart = 30)  

 
shots_clean |>
   mutate(cluster = factor(second_kmeans$cluster)) |>
   ggplot(aes(x = location_x, 
              y = location_y, 
              color = cluster)) +
   geom_point(size = 2) +
   ggthemes::scale_color_colorblind()


shots_made_orig <- shots |> 
  filter(goal == "Goal") |> 
  select(location_x, location_y)

shots_scaled <- as.data.frame(scale(shots_made_orig))

first_kmeans <- kmeans(shots_scaled, 
                       centers = 4, 
                       nstart = 100)


shots_made_orig$cluster <- factor(first_kmeans$cluster)


ggplot(shots_made_orig, aes(x = location_x, y = location_y, color = cluster)) +
  annotate_pitch(dimensions = pitch_statsbomb, fill = "#F8F8F8", colour = "#CCCCCC") +
  geom_point(size = 3, alpha = 0.7) +
  coord_fixed(xlim = c(60, 120), ylim = c(0, 80)) +  # right half of pitch
  ggthemes::scale_color_colorblind() +
  labs(title = "K-Means Clusters of Made Shots",
       color = "Cluster") +
  theme_void()
```


```{r}

```



```{r}
  
# ideas for potential research questions:

#without facet 
ggplot(data = shots, 
       aes(x = location_x, 
           y = location_y, 
           color = goal)) +
  geom_point(alpha = 0.5, size = 2) +
  coord_fixed() +  # keeps aspect ratio square
  scale_color_manual(values = c("Miss" = "gray70", "Goal" = "red")) +
  labs(title = "Shot location by outcome",
       x = "",
       y = "",
       color = "Outcome") +
  theme_void()
```


